name: build
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'koyeb-community'
    steps:
      - uses: actions/checkout@v2
      - uses: koyeb-community/catalog-builder@master
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
